# Generated by Django 2.2.6 on 2020-03-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_watch_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='watch_list',
        ),
    ]
