# Generated by Django 2.2.6 on 2020-02-10 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0003_auto_20200209_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default_item.jpg', upload_to='item_pics'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 10, 17, 54, 11, 228203)),
        ),
    ]
