# Generated by Django 2.2.6 on 2020-02-10 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_auto_20200210_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 10, 21, 9, 35, 3982)),
        ),
        migrations.CreateModel(
            name='Item_Pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_pics')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Item')),
            ],
        ),
    ]
