# Generated by Django 2.2.6 on 2020-02-11 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0005_auto_20200210_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 11, 14, 19, 48, 412492)),
        ),
    ]
