# Generated by Django 2.2.6 on 2020-02-11 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0006_auto_20200211_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 11, 20, 51, 7, 752795)),
        ),
    ]
