# Generated by Django 2.2.6 on 2020-02-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_auto_20200211_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
