# Generated by Django 3.0.5 on 2020-05-14 22:26

import bazaar.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, "Are you OK?! Price can't be lesser than %(limit_value)s!")], verbose_name='price')),
                ('end_of_auction', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 22, 26, 5, 351360, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 5, 14, 22, 26, 5, 351372, tzinfo=utc), "You can't set end of auction in the past.")], verbose_name='end of auction')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USE', 'Used'), ('REF', 'Refurbished'), ('NOT', 'For parts or not working')], default='USE', max_length=3, verbose_name='condition')),
                ('main_image', models.ImageField(default='default_item.jpg', upload_to=bazaar.models.get_path_for_my_model_file, verbose_name='thumbnail')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watch_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='bazaar.Item', verbose_name='watch list')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_item.jpg', upload_to=bazaar.models.get_path_for_my_model_file)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, "Are you OK?! Price can't be lesser than %(limit_value)s!")], verbose_name='new price')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='bazaar.Item')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bid_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
