# Generated by Django 2.2.6 on 2020-03-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_watch_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch_list',
            old_name='watch_list',
            new_name='items',
        ),
    ]
