# Generated by Django 2.2.6 on 2020-03-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_item_end_of_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_of_auction',
            field=models.DateTimeField(verbose_name='end of auction'),
        ),
    ]
