# Generated by Django 2.2.6 on 2020-03-27 15:41

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_auto_20200323_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_of_auction',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 15, 41, 3, 205822, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 3, 27, 15, 41, 3, 205835, tzinfo=utc), "You can't set end of auction in the past.")], verbose_name='end of auction'),
        ),
    ]
