# Generated by Django 2.2.6 on 2020-03-08 19:11

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0006_auto_20200308_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_of_auction',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 19, 11, 33, 428354, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 3, 8, 19, 11, 33, 428366, tzinfo=utc), "You can't set end of auction in the past.")], verbose_name='end of auction'),
        ),
    ]
