# Generated by Django 2.2.6 on 2020-04-03 13:15

import bazaar.models
import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0006_auto_20200327_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_of_auction',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 13, 15, 28, 341400, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 4, 3, 13, 15, 28, 341413, tzinfo=utc), "You can't set end of auction in the past.")], verbose_name='end of auction'),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(default='default_item.jpg', upload_to=bazaar.models.get_path_for_my_model_file, verbose_name='thumbnail'),
        ),
    ]
