# Generated by Django 3.0.5 on 2020-04-04 13:47

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_auto_20200403_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USE', 'Used'), ('REF', 'Refurbished'), ('NOT', 'For parts or not working')], default='USE', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_of_auction',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 13, 47, 33, 927607, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 4, 4, 13, 47, 33, 927621, tzinfo=utc), "You can't set end of auction in the past.")], verbose_name='end of auction'),
        ),
    ]
