# Generated by Django 2.2.6 on 2020-03-08 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_auto_20200308_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_of_auction',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 19, 14, 24, 344082, tzinfo=utc), verbose_name='end of auction'),
        ),
    ]
