# Generated by Django 3.0.5 on 2020-05-07 01:11

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazaar', '0008_auto_20200404_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='bazaar.Item'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bid_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USE', 'Used'), ('REF', 'Refurbished'), ('NOT', 'For parts or not working')], default='USE', max_length=3, verbose_name='condition'),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_of_auction',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 1, 11, 20, 926359, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 5, 7, 1, 11, 20, 926373, tzinfo=utc), "You can't set end of auction in the past.")], verbose_name='end of auction'),
        ),
    ]
