# Generated by Django 2.2.6 on 2020-03-09 20:16

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazaar', '0009_auto_20200308_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_of_auction',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 20, 16, 29, 300333, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 3, 9, 20, 16, 29, 300345, tzinfo=utc), "You can't set end of auction in the past.")], verbose_name='end of auction'),
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, "Are you OK?! Price can't be lesser than %(limit_value)s!")], verbose_name='price')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 3, 9, 20, 16, 29, 302747, tzinfo=utc))),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Item')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
