# Generated by Django 3.0.5 on 2020-05-07 01:41

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0009_auto_20200507_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_of_auction',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 1, 41, 22, 723534, tzinfo=utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 5, 7, 1, 41, 22, 723547, tzinfo=utc), "You can't set end of auction in the past.")], verbose_name='end of auction'),
        ),
    ]
